import {
  Braces,
  Building2,
  CaseSensitive,
  Columns2,
  Copy,
  Droplet,
  Eraser,
  Filter,
  Globe,
  Mail,
  Merge,
  PencilLine,
  Phone,
  Regex,
  Replace,
  Scissors,
  Sparkles,
  Spline,
  User,
} from 'lucide-react'

/** Maps operation icon names (from utils/scrubbers.js) to lucide components. */
export const OP_ICONS = {
  scissors: Scissors,
  eraser: Eraser,
  copy: Copy,
  'case-sensitive': CaseSensitive,
  mail: Mail,
  phone: Phone,
  droplet: Droplet,
  columns: Columns2,
  'pencil-line': PencilLine,
  replace: Replace,
  spline: Spline,
  merge: Merge,
  filter: Filter,
  globe: Globe,
  building: Building2,
  user: User,
  regex: Regex,
  braces: Braces,
  sparkles: Sparkles,
}
